spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/local
    username: root
    password: root
    driverClassName: org.postgresql.Driver

  elasticsearch:
    uris: http://localhost:9200

  batch:
    job:
      enabled: true