version: "3.8"

services:

  postgresql:
    image: postgres:16.3
    container_name: postgresql
    environment:
      POSTGRES_USER: "root"
      POSTGRES_PASSWORD: "root"
      POSTGRES_DB: "local"
    ports:
      - "5432:5432"
    volumes:
      - dbvol:/var/lib/postgresql/data
      - ./initdb:/docker-entrypoint-initdb.d

volumes:
  dbvol: